// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNRA5i0cCr6ehSibpBnOR7eY-1TCeb9k',
    appId: '1:448509671387:web:eddc8691f511582c89d9fe',
    messagingSenderId: '448509671387',
    projectId: 'appsprojectbi',
    authDomain: 'appsprojectbi.firebaseapp.com',
    storageBucket: 'appsprojectbi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyrB51W3QrFqGUYwEn0rXnxzS-zvnMLso',
    appId: '1:448509671387:android:46eadf68467d24a689d9fe',
    messagingSenderId: '448509671387',
    projectId: 'appsprojectbi',
    storageBucket: 'appsprojectbi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VyJl2ZgXKcEyOtOl_xbszxRob-0i_RU',
    appId: '1:448509671387:ios:1e2896d8d6f03bd589d9fe',
    messagingSenderId: '448509671387',
    projectId: 'appsprojectbi',
    storageBucket: 'appsprojectbi.firebasestorage.app',
    iosBundleId: 'com.example.appAndroid001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VyJl2ZgXKcEyOtOl_xbszxRob-0i_RU',
    appId: '1:448509671387:ios:1e2896d8d6f03bd589d9fe',
    messagingSenderId: '448509671387',
    projectId: 'appsprojectbi',
    storageBucket: 'appsprojectbi.firebasestorage.app',
    iosBundleId: 'com.example.appAndroid001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMNRA5i0cCr6ehSibpBnOR7eY-1TCeb9k',
    appId: '1:448509671387:web:ad2807f5ce8d822689d9fe',
    messagingSenderId: '448509671387',
    projectId: 'appsprojectbi',
    authDomain: 'appsprojectbi.firebaseapp.com',
    storageBucket: 'appsprojectbi.firebasestorage.app',
  );
}
